// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keidkjvlwfyroqyzsocf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlaWRranZsd2Z5cm9xeXpzb2NmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NDM4MzUsImV4cCI6MjA1MDAxOTgzNX0.E4ElKslFX6wtvXeUpTSAsq4XYn_r9cnoq2bz7Xd0AxE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);